### ISSUE TITLE
Feature Request: Span Event Handling

### ISSUE THREAD

**Issue by c2nes** [honeycombio/opentelemetry-exporter-go#1]
In the [Honeycomb OpenCensus Exporter](https://github.com/honeycombio/opencensus-exporter/), annotations and message events for a span are exported to Honeycomb as a serialized JSON array attached to the event as a field.

When the OpenTelemetry exporter is developed I think it would be valuable to have the option to instead report each Span Event as a separate Honeycomb Event.

I've [prototyped](https://github.com/c2nes/opencensus-service/commit/77b5f59c25b2b77a208e0c6ea53d9976a863f387) something similar in the OpenCensus exporter for annotations. By setting the trace ID and parent span ID in the event for each annotation (and omitting a span ID) I was able to get the annotation to show up on the Honeycomb Trace view (they look like a spans with 0s duration).

**Comment by maplebed** [comment]
Yes, absolutely. I am on board with this plan. I have hopes that once this happens we'll be able to also augment the Honeycomb trace waterfall view to handle this data type more gracefully given its unique relationship to its parent span.
I think rather than omit the span ID I would retain a unique span ID, set `duration_ms` to 0, and add an additional field indicating this is a span event and not a regular span. But those details can easily be worked out during implementation. 

Thanks!
