### ISSUE TITLE
Metrics exporter

### ISSUE THREAD

**Issue by alexrudd** [honeycombio/opentelemetry-exporter-go#89]
Hi,

We've been using the trace exporter and it's been working great, thank you! We were wondering if there are plans to implement a [metrics exporter](https://pkg.go.dev/go.opentelemetry.io/otel/sdk@v0.10.0/export/metric?tab=doc#Exporter) too?

Our use case is for exporting runtime metrics such as the contents of [MemStats](https://pkg.go.dev/runtime?tab=doc#MemStats). Currently we're attaching all those values to every span using `WithDynamicField` but that seems wrong.

Thanks

**Comment by lizthegrey** [comment]
WithDynamicField actually is exactly what we do at Honeycomb for observing those gauges. It's free since we charge by the event, not by the field.

In the long term, yeah, it would be neat to have a push dataset that receives counter/gauge values once per minute etc. -- so we'll put this on our requested feature backlog.

**Comment by alexrudd** [comment]
Thanks, we'll keep using WithDynamicField but it's good to know metrics support might be coming in the future :)

**Comment by JamieDanielson** [comment]
This project is set to sunset - see issue #105. If this exporter is still actively used, please comment on the sunset issue.
